"""Check or generate a dangerous Codex YOLO startup task draft.

By default this script does not register a startup task. It checks whether the
task exists and, when missing, generates auditable local task-registration
artifacts. Actual registration requires both --register and
--i-understand-dangerous-yolo-startup.
"""



from __future__ import annotations

# A+B layering: real module lives in scripts/commands/; keep scripts root importable.
import sys
from pathlib import Path
_SCRIPTS_ROOT = str(Path(__file__).resolve().parents[1])
if _SCRIPTS_ROOT not in sys.path:
    sys.path.insert(0, _SCRIPTS_ROOT)


import argparse
import json
from pathlib import Path
import platform
import shutil
import subprocess
import sys
from datetime import datetime

sys.dont_write_bytecode = True

from shiguan_paths import reference_path


DEFAULT_TASK_NAME = "CodexYoloStartup"
DEFAULT_TASK_PATH = "\\CodexCourt\\"
YOLO_ARG = "--dangerously-bypass-approvals-and-sandbox"


def skill_root() -> Path:
    return Path(__file__).resolve().parents[2]


def output_root() -> Path:
    root = reference_path("startup-tasks")
    root.mkdir(parents=True, exist_ok=True)
    return root


def default_log_dir() -> Path:
    return Path.home() / ".codex" / "logs" / "decretum-matrix"


def is_windows() -> bool:
    return platform.system().lower() == "windows"


def task_full_name(task_path: str, task_name: str) -> str:
    normalized_path = task_path
    if not normalized_path.startswith("\\"):
        normalized_path = "\\" + normalized_path
    if not normalized_path.endswith("\\"):
        normalized_path += "\\"
    return f"{normalized_path}{task_name}"


def task_exists(full_name: str) -> tuple[bool, str]:
    if not is_windows():
        return False, "Windows Task Scheduler is not available on this host"
    try:
        result = subprocess.run(
            ["schtasks", "/Query", "/TN", full_name],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, f"schtasks query failed: {exc}"
    if result.returncode == 0:
        return True, "task exists"
    detail = (result.stderr or result.stdout or "").strip()
    if "cannot find the file specified" in detail.lower() or "找不到" in detail:
        detail = "task not found"
    return False, detail or "task not found"


def quote_ps(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_artifacts(
    task_name: str,
    task_path: str,
    codex_exe: str,
    workdir: str,
    log_dir: str,
) -> tuple[Path, Path, Path, Path, Path]:
    root = output_root()
    script_path = root / f"{task_name}.register.ps1"
    unregister_path = root / f"{task_name}.unregister.ps1"
    metadata_path = root / f"{task_name}.json"
    wrapper_path = Path(log_dir) / f"{task_name}.runner.ps1"
    log_path = Path(log_dir) / f"{task_name}.log"
    command_preview = f"{codex_exe} {YOLO_ARG}"
    now = datetime.now().isoformat(timespec="seconds")

    wrapper = f"""$ErrorActionPreference = 'Continue'
$LogPath = {quote_ps(str(log_path))}
$LaunchLine = {quote_ps(command_preview)}
$Stamp = Get-Date -Format o
"[$Stamp] Launching $LaunchLine" | Out-File -FilePath $LogPath -Append -Encoding utf8
& {quote_ps(codex_exe)} {quote_ps(YOLO_ARG)} *>> $LogPath
$Exit = $LASTEXITCODE
$Stamp = Get-Date -Format o
"[$Stamp] Codex exited with $Exit" | Out-File -FilePath $LogPath -Append -Encoding utf8
exit $Exit
"""

    script = f"""# Generated by Decretum Matrix.
# WARNING: This registers Codex to start at logon with no sandbox and no approval prompts.
# Review the command and path before running.
$TaskName = {quote_ps(task_name)}
$TaskPath = {quote_ps(task_path)}
$WorkDir = {quote_ps(workdir)}
$LogDir = {quote_ps(log_dir)}
$WrapperPath = {quote_ps(str(wrapper_path))}
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
$Wrapper = @'
{wrapper.rstrip()}
'@
Set-Content -Path $WrapperPath -Value $Wrapper -Encoding UTF8
$ActionArgument = '-NoProfile -ExecutionPolicy Bypass -File "' + $WrapperPath + '"'
$Action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument $ActionArgument -WorkingDirectory $WorkDir
$Trigger = New-ScheduledTaskTrigger -AtLogOn
$Description = 'Starts Codex at logon with --dangerously-bypass-approvals-and-sandbox. Generated by Decretum Matrix.'
Register-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath -Action $Action -Trigger $Trigger -Description $Description -Force
"""
    script_path.write_text(script, encoding="utf-8", newline="\n")

    unregister = f"""# Generated by Decretum Matrix.
# Revoke the dangerous Codex YOLO startup task.
$TaskName = {quote_ps(task_name)}
$TaskPath = {quote_ps(task_path)}
Unregister-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath -Confirm:$false
"""
    unregister_path.write_text(unregister, encoding="utf-8", newline="\n")

    metadata = {
        "created_at": now,
        "risk": "DANGEROUS_NO_SANDBOX_NO_APPROVAL_STARTUP",
        "risk_detail": "No-sandbox autostart requires explicit confirmation before registration.",
        "task_name": task_name,
        "task_path": task_path,
        "task_full_name": task_full_name(task_path, task_name),
        "trigger": "AtLogOn",
        "codex_exe": codex_exe,
        "workdir": workdir,
        "command_preview": command_preview,
        "scheduled_action_execute": "powershell.exe",
        "scheduled_action_argument": f'-NoProfile -ExecutionPolicy Bypass -File "{wrapper_path}"',
        "log_path": str(log_path),
        "wrapper_script": str(wrapper_path),
        "register_script": str(script_path),
        "unregister_script": str(unregister_path),
        "manual_registration": f"powershell -ExecutionPolicy Bypass -File {script_path}",
        "manual_revoke": f"powershell -ExecutionPolicy Bypass -File {unregister_path}",
        "registration_requires_explicit_user_confirmation": True,
    }
    metadata_path.write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return script_path, unregister_path, metadata_path, wrapper_path, log_path


def register_task(script_path: Path) -> tuple[bool, str]:
    try:
        result = subprocess.run(
            [
                "powershell",
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                str(script_path),
            ],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, f"registration command failed: {exc}"
    if result.returncode == 0:
        return True, (result.stdout or "registered").strip()
    return False, (result.stderr or result.stdout or "registration failed").strip()


def report(status: str, **values: object) -> dict[str, object]:
    payload: dict[str, object] = {"status": status}
    payload.update(values)
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task-name", default=DEFAULT_TASK_NAME)
    parser.add_argument("--task-path", default=DEFAULT_TASK_PATH)
    parser.add_argument("--codex-exe", default=shutil.which("codex") or "codex")
    parser.add_argument("--workdir", default=str(Path.home()))
    parser.add_argument("--log-dir", default=str(default_log_dir()))
    parser.add_argument("--check-only", action="store_true")
    parser.add_argument("--register", action="store_true")
    parser.add_argument("--i-understand-dangerous-yolo-startup", action="store_true")
    args = parser.parse_args()

    full_name = task_full_name(args.task_path, args.task_name)
    exists, reason = task_exists(full_name)
    base = {
        "task_full_name": full_name,
        "task_name": args.task_name,
        "task_path": args.task_path,
        "codex_exe": args.codex_exe,
        "workdir": args.workdir,
        "log_dir": args.log_dir,
        "dangerous_command": f"{args.codex_exe} {YOLO_ARG}",
        "reason": reason,
    }
    if exists:
        print(json.dumps(report("TASK_EXISTS", **base), ensure_ascii=False, sort_keys=True))
        return 0
    if args.check_only:
        print(json.dumps(report("MISSING", **base), ensure_ascii=False, sort_keys=True))
        return 0

    script_path, unregister_path, metadata_path, wrapper_path, log_path = write_artifacts(
        args.task_name,
        args.task_path,
        args.codex_exe,
        args.workdir,
        args.log_dir,
    )
    base.update(
        {
            "register_script": str(script_path),
            "unregister_script": str(unregister_path),
            "metadata_path": str(metadata_path),
            "wrapper_script": str(wrapper_path),
            "log_path": str(log_path),
            "manual_revoke": f"powershell -ExecutionPolicy Bypass -File {unregister_path}",
        }
    )

    if args.register:
        if not args.i_understand_dangerous_yolo_startup:
            print(
                json.dumps(
                    report(
                        "REGISTRATION_REFUSED",
                        **base,
                        remediation="rerun with --register --i-understand-dangerous-yolo-startup after explicit user approval",
                    ),
                    ensure_ascii=False,
                    sort_keys=True,
                )
            )
            return 2
        ok, detail = register_task(script_path)
        status = "REGISTERED" if ok else "FAILED"
        print(json.dumps(report(status, **base, registration_detail=detail), ensure_ascii=False, sort_keys=True))
        return 0 if ok else 3

    print(
        json.dumps(
            report(
                "GENERATED_REVIEW_TASK",
                **base,
                remediation="review the generated PowerShell script; actual registration requires explicit dangerous startup approval",
            ),
            ensure_ascii=False,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())

